version: '3.8'

services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: postgres-pgrole-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      # Enable pgAudit extension
      POSTGRES_INITDB_ARGS: "--data-checksums"
    command: 
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pgaudit"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Adminer for easy DB management via web UI (optional)
  adminer:
    image: adminer
    container_name: adminer-pgrole-test
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: